// <auto-generated />
using System;
using FinancialGoal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialGoal.Infrastructure.Persistence.Migration
{
    [DbContext(typeof(ObjetivoFinanceiroDbContext))]
    partial class ObjetivoFinanceiroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialGoal.Core.Entities.ObjetivoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("EstaDeletado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("QuantidadeAlvo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusObj")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjetivoFinanceiro");
                });

            modelBuilder.Entity("FinancialGoal.Core.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTransacao")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("EstaDeletado")
                        .HasColumnType("bit");

                    b.Property<int>("IdObjetivo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdObjetivo");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("FinancialGoal.Core.Entities.Transacao", b =>
                {
                    b.HasOne("FinancialGoal.Core.Entities.ObjetivoFinanceiro", "ObjetivoFinanceiro")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdObjetivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjetivoFinanceiro");
                });

            modelBuilder.Entity("FinancialGoal.Core.Entities.ObjetivoFinanceiro", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
